"""Agregar first_name y last_name a User

Revision ID: 02b13edb3795
Revises: e376dd61e346
Create Date: 2025-09-27 01:55:30.700575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b13edb3795'
down_revision = 'e376dd61e346'
branch_labels = None
depends_on = None


def upgrade():
    
    with op.batch_alter_table('User') as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))

    # Opcional: rellenar datos existentes con algún valor
    op.execute("UPDATE \"User\" SET first_name = 'Default', last_name = 'User' WHERE first_name IS NULL OR last_name IS NULL")

    with op.batch_alter_table('User') as batch_op:
        batch_op.alter_column('first_name', nullable=False)
        batch_op.alter_column('last_name', nullable=False)
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
    # ### end Alembic commands ###
