"""Nueva migración

Revision ID: 21128261bcc4
Revises: 06e1aa23b5e8
Create Date: 2025-10-06 23:31:53.495092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21128261bcc4'
down_revision = '06e1aa23b5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Flag')
    # ### end Alembic commands ###
