"""add site images

Revision ID: add_site_images_001
Revises: 3608e1af4698
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'add_site_images_001'
down_revision = '3608e1af4698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Site_Image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_site', sa.Integer(), nullable=False),
    sa.Column('url_publica', sa.String(length=500), nullable=False),
    sa.Column('titulo_alt', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('es_portada', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['id_site'], ['Historic_Site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Site_Image')
    # ### end Alembic commands ###

