"""Add updated_at to HistoricSiteReview

Revision ID: 3656f775392f
Revises: 5c37bd1c72c8
Create Date: 2025-12-01 20:50:22.099923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3656f775392f'
down_revision = '5c37bd1c72c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Historic_Site_Review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Historic_Site_Review', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
