"""fix_merge_user_columns

Revision ID: 552c216821aa
Revises: 5c37bd1c72c8
Create Date: 2025-11-20 10:03:43.710416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552c216821aa'
down_revision = '5c37bd1c72c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_super_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('is_superadmin')

    # ### end Alembic commands ###
