"""Implement Joined Table Inheritance for User model

Revision ID: a7b77b58a3e5
Revises: 3656f775392f
Create Date: 2025-12-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a7b77b58a3e5'
down_revision = '3656f775392f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Agregar columna 'type' a la tabla User (discriminador polimórfico)
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
    
    # 2. Establecer valor por defecto 'private' para usuarios existentes
    # (todos los usuarios actuales son privados según el contexto del proyecto)
    op.execute('UPDATE "User" SET type = \'private\' WHERE type IS NULL')
    
    # 3. Hacer la columna 'type' NOT NULL después de establecer valores
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('type', nullable=False)
    
    # 4. Crear tabla Private_User con campos privados
    op.create_table('Private_User',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('blocked', sa.Boolean(), nullable=True),
        sa.Column('is_super_admin', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['User.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 5. Migrar datos de usuarios existentes a Private_User
    # Todos los usuarios actuales son privados, así que migramos todos
    op.execute("""
        INSERT INTO "Private_User" (id, password, active, blocked, is_super_admin)
        SELECT id, password, active, blocked, COALESCE(is_super_admin, false)
        FROM "User"
        WHERE type = 'private'
    """)
    
    # 6. Crear tabla Public_User con campo avatar_url
    op.create_table('Public_User',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('avatar_url', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['User.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 7. Remover campos privados y avatar_url de la tabla User (ya que ahora están en las tablas hijas)
    # NOTA: Solo eliminamos las columnas después de haber migrado los datos a las tablas hijas
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('active')
        batch_op.drop_column('blocked')
        batch_op.drop_column('is_super_admin')
        batch_op.drop_column('avatar_url')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Restaurar campos privados y avatar_url a la tabla User
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
    
    # 2. Restaurar datos de Private_User a User
    op.execute("""
        UPDATE "User" u
        SET 
            password = pu.password,
            active = pu.active,
            blocked = pu.blocked,
            is_super_admin = pu.is_super_admin
        FROM "Private_User" pu
        WHERE u.id = pu.id
    """)
    
    # 3. Restaurar datos de Public_User a User
    op.execute("""
        UPDATE "User" u
        SET avatar_url = pu.avatar_url
        FROM "Public_User" pu
        WHERE u.id = pu.id
    """)
    
    # 4. Eliminar tablas hijas
    op.drop_table('Public_User')
    op.drop_table('Private_User')
    
    # 5. Eliminar columna type
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('type')
    
    # ### end Alembic commands ###

