"""Cambiar restricciÃ³n Ãºnica de mail a Ã­ndice Ãºnico en type y mail

Revision ID: b17fee5ff915
Revises: 4b72c07dd522
Create Date: 2025-12-13 17:33:24.376432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17fee5ff915'
down_revision = '4b72c07dd522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('User_mail_key'), type_='unique')
        batch_op.create_index('idx_user_type_mail_unique', ['type', 'mail'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('idx_user_type_mail_unique')
        batch_op.create_unique_constraint(batch_op.f('User_mail_key'), ['mail'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
