"""user soft-delete audit fields

Revision ID: b67685236135
Revises: 21128261bcc4
Create Date: 2025-11-02 16:50:33.646080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67685236135'
down_revision = '21128261bcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deletion_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deletion_reason')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
