"""check for pending changes

Revision ID: d8220148a9ab
Revises: add_site_images_001
Create Date: 2025-11-19 08:55:41.665593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8220148a9ab'
down_revision = 'add_site_images_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Historic_Site_Review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Historic_Site_Review', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
