"""Initial migration

Revision ID: e100c64e414e
Revises: 
Create Date: 2025-09-19 15:26:08.275004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e100c64e414e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category_Site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Rol_User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('State_Site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('City',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_province', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_province'], ['Province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Permission_Rol_User',
    sa.Column('Permission_id', sa.Integer(), nullable=False),
    sa.Column('Rol_User_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Permission_id'], ['Permission.id'], ),
    sa.ForeignKeyConstraint(['Rol_User_id'], ['Rol_User.id'], ),
    sa.PrimaryKeyConstraint('Permission_id', 'Rol_User_id')
    )
    op.create_table('Rol_User_User',
    sa.Column('Rol_User_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Rol_User_id'], ['Rol_User.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('Rol_User_id', 'User_id')
    )
    op.create_table('Historic_Site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brief_description', sa.Text(), nullable=False),
    sa.Column('complete_description', sa.Text(), nullable=True),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=True),
    sa.Column('year_inauguration', sa.Integer(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['Category_Site.id'], ),
    sa.ForeignKeyConstraint(['id_ciudad'], ['City.id'], ),
    sa.ForeignKeyConstraint(['id_estado'], ['State_Site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_site', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('type_Action', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_site'], ['Historic_Site.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tag_Historic_Site',
    sa.Column('Tag_id', sa.Integer(), nullable=False),
    sa.Column('Historic_Site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Historic_Site_id'], ['Historic_Site.id'], ),
    sa.ForeignKeyConstraint(['Tag_id'], ['Tag.id'], ),
    sa.PrimaryKeyConstraint('Tag_id', 'Historic_Site_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tag_Historic_Site')
    op.drop_table('Event')
    op.drop_table('Historic_Site')
    op.drop_table('Rol_User_User')
    op.drop_table('Permission_Rol_User')
    op.drop_table('City')
    op.drop_table('User')
    op.drop_table('Tag')
    op.drop_table('State_Site')
    op.drop_table('Rol_User')
    op.drop_table('Province')
    op.drop_table('Permission')
    op.drop_table('Category_Site')
    # ### end Alembic commands ###
